logging:
    level:
        org:
            springframework:
                web: INFO

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
            connection-init-sql: SELECT 1
            connection-timeout: 36000000
            idle-timeout: 0
            maximum-pool-size: 10
            poolName: najahr-pool
        password: admin
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/najahr
        username: postgres
    jmx:
        default-domain: najahr-app
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hiberante:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        show-sql: true

server:
    servlet:
        context-path: /najahhrserver
    error:
        include-stacktrace: never



