logging:
    level:
        org:
            springframework:
                web: INFO

spring:
    datasource:
#        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
            connection-init-sql: SELECT 1
            connection-timeout: 36000000
            idle-timeout: 0
            maximum-pool-size: 10
            poolName: najahr-pool
        password: admin
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/najahr
        username: postgres
    password: admin
    username: postgres
    jmx:
        default-domain: najahr-app
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hiberante:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        show-sql: true
        database: POSTGRESQL
    cloud:
        gcp:
            sql:
                enabled: true
                database-name: najahr
                instance-connection-name: najahrbackend:us-central1:najahr
#        credentials:
#            locations: classpath://najahrbackend-3bd3911302b9.json

server:
    servlet:
        context-path: /najahhrserver
    error:
        include-stacktrace: never



