logging:
    level:
        org:
            springframework:
                web: INFO

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
            connection-init-sql: SELECT 1
            connection-timeout: 36000000
            idle-timeout: 0
            maximum-pool-size: 10
            poolName: najahr-pool
        password: admin
        type: com.zaxxer.hikari.HikariDataSource
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    jmx:
        default-domain: najahr-app
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hiberante:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
        show-sql: true
        database: POSTGRESQL

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASS}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true

server:
    error:
        include-stacktrace: never



